[colors.bright]
black   = '#686868'
red     = '#ff4f58'
green   = '#73c936'
yellow  = '#ffdd33'
blue    = '#96a6c8'
magenta = '#9e95c7'
cyan    = '#96a6c8'
white   = '#ffffff'

[colors.cursor]
cursor = "#9ea7a6"
text = "#232c31"

[colors.normal]
black   = '#000000'
red     = '#f43841'
green   = '#73c936'
yellow  = '#ffdd33'
blue    = '#5f627f'
magenta = '#9e95c7'
cyan    = '#5f627f'
white   = '#ffffff'

[colors.primary]
background = '#181818'
foreground = '#e4e4ef'

[font]
size = 10

[font.bold]
family = "Comic Code"
style = "Bold"

[font.bold_italic]
family = "Comic Code"
style = "Bold Italic"

[font.italic]
family = "Comic Code"
style = "Italic"

[font.normal]
family = "Comic Code"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
opacity = 1.0
