# theme = "Codeschool.dark"

[colors]
# author = "Chris Kempson"
# name = "Codeschool (dark)"

[colors.bright]
black = "#3f4944"
blue = "#484d79"
cyan = "#b02f30"
green = "#237986"
magenta = "#c59820"
red = "#2a5491"
white = "#b5d8f6"
yellow = "#a03b1e"

[colors.cursor]
cursor = "#9ea7a6"
text = "#232c31"

[colors.normal]
black = "#232c31"
blue = "#484d79"
cyan = "#b02f30"
green = "#237986"
magenta = "#c59820"
red = "#2a5491"
white = "#9ea7a6"
yellow = "#a03b1e"

[colors.primary]
background = "#232c31"
foreground = "#9ea7a6"

[font]
size = 13

[font.bold]
family = "MonaspiceArNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "MonaspiceArNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "MonaspiceArNerdFontMono"
style = "Italic"

[font.normal]
family = "MonaspiceArNerdFontMono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
opacity = 1.0
