theme = "gruber-darker"
[editor.soft-wrap]
enable = true
[editor]
line-number = "relative"
true-color=true
[keys.insert]
j = {k = "normal_mode"}
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.whitespace.render]
space = "all"
tab = "all"

